version: '3'
services:
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
    ports:
      - "3306:3306"
    volumes:
      - drupal_db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  drupal_db_data: 